name: cloudchasers-pipeline
on: workflow_dispatch

jobs:
  build-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - name: get pem file
        run: |
          echo "${{ secrets.sheela_key}}" > sheela--r.pem
          chmod 400 sheela--r.pem
          ls -lrsth
      - name: cp app.py
        run: scp -o StrictHostKeyChecking=no -i sheela--r.pem app.py ec2-user@13.233.173.99:/home/ec2-user/
      - name: cp req.txt
        run: scp -o StrictHostKeyChecking=no -i sheela--r.pem requirements.txt ec2-user@13.233.173.99:/home/ec2-user/ 
      - name: run app
        run: ssh -o StrictHostKeyChecking=no -i sheela--r.pem ec2-user@13.233.173.99 "cd /home/ec2-user && python3 -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt && python3 app.py"
        
